# k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diplom-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diplom-test-app
  template:
    metadata:
      labels:
        app: diplom-test-app
    spec:
      imagePullSecrets:
        - name: yc-cr-creds
      containers:
        - name: diplom-test-app
          image: omegavlg/diplom-test-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: diplom-test-app
spec:
  type: NodePort
  selector:
    app: diplom-test-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32001
